name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Code Quality
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

      SMTP_HOST: localhost
      SMTP_PORT: 1025
      SMTP_USERNAME: test_user
      SMTP_PASSWORD: test_password
      SMTP_FROM: test@example.com

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Setup Python 3.13
        run: uv python install 3.13

      - name: Install Dependencies
        run: uv sync --dev

      - name: Run Pylint
        run: uv run pylint . --verbose --fail-under=9
      
      - name: Run test and coverage
        run: uv run pytest --cov=. --cov-report=term-missing --cov-report=html --cov-fail-under=95
      
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

          