name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Setup Python 3.13
        run: uv python install 3.13

      - name: Install Dependencies
        run: uv sync --dev

      - name: Run Pylint
        run: uv run pylint . --verbose --fail-under=9
      
      - name: Run test and coverage
        run: uv run pytest --cov=. --cov-report=term-missing --cov-report=html --cov-fail-under=95

          